// Copyright (c) 2021 - 2022, Nemes <nemes@nemez.net>
// SPDX-License-Identifier: MIT
// 
// MIT License
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software andassociated documentation files(the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, andto permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
// 
// The above copyright notice andthis permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#include "main.h"
#include "logger.h"
#include <stdarg.h>

#define DEFINE_STATUS_CASE(status)  case status: return #status

test_status LoggerLogMessage(const char *format, ...) {
    va_list list;
    va_start(list, format);
    vprintf(format, list);
    va_end(list);
    fflush(stdout);
    return TEST_OK;
}

const char *LoggerLookUpError(test_status status) {
    switch (status) {
        DEFINE_STATUS_CASE(TEST_OK);
        DEFINE_STATUS_CASE(TEST_UNKNOWN_ERROR);
        DEFINE_STATUS_CASE(TEST_OUT_OF_MEMORY);
        DEFINE_STATUS_CASE(TEST_FILE_NOT_FOUND);
        DEFINE_STATUS_CASE(TEST_FILE_IO_ERROR);
        DEFINE_STATUS_CASE(TEST_INVALID_PARAMETER);
        DEFINE_STATUS_CASE(TEST_UNKNOWN_TESTCASE);
        DEFINE_STATUS_CASE(TEST_UNKNOWN_DEVICE);
        DEFINE_STATUS_CASE(TEST_NO_TEST_SPECIFIED);
        DEFINE_STATUS_CASE(TEST_PRINTF_FORMAT_ERROR);
        DEFINE_STATUS_CASE(TEST_OUT_OF_RANGE);
        DEFINE_STATUS_CASE(TEST_PROGRAMMING_ERROR);
        DEFINE_STATUS_CASE(TEST_FAILED_TO_SPAWN_TEST_PROCESS);
        DEFINE_STATUS_CASE(TEST_FAILED_TO_INITIALIZE_GLFW);
        DEFINE_STATUS_CASE(TEST_FAILED_TO_INITIALIZE_GLEW);
        DEFINE_STATUS_CASE(TEST_FAILED_TO_INITIALIZE_IMGUI);
        DEFINE_STATUS_CASE(TEST_FAILED_TO_CREATE_WINDOW);
        DEFINE_STATUS_CASE(TEST_FAILED_TO_SPAWN_THREAD);
        DEFINE_STATUS_CASE(TEST_ASYNC_PROCESS_RUNNING);
        DEFINE_STATUS_CASE(TEST_PROCESS_KILLED);
        DEFINE_STATUS_CASE(TEST_EMBEDDED_RESOURCE_NOT_FOUND);
        DEFINE_STATUS_CASE(TEST_FAILED_TO_LOAD_WINDOW_ICON);
        DEFINE_STATUS_CASE(TEST_FAILED_TO_DECODE_WINDOW_ICON);

        DEFINE_STATUS_CASE(TEST_VK_CREATE_INSTANCE_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_LAYER_ENUMERATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_LAYER_UNSUPPORTED);
        DEFINE_STATUS_CASE(TEST_VK_DEBUG_MESSENGER_CREATE_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_DEBUG_UTILS_PROC_ADDR_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_DEVICE_ENUMERATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_QUEUE_NOT_FOUND);
        DEFINE_STATUS_CASE(TEST_VK_DEVICE_CREATE_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_SUITABLE_ALLOCATION_NOT_FOUND);
        DEFINE_STATUS_CASE(TEST_VK_MEMORY_ALLOCATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_BUFFER_CREATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_BUFFER_BIND_MEMORY_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_SHADER_MODULE_CREATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_PIPELINE_LAYOUT_CREATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_COMPUTE_PIPELINE_CREATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_DESCRIPTOR_SET_LAYOUT_CREATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_DESCRIPTOR_POOL_CREATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_DESCRIPTOR_SET_ALLOCATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_COMMAND_POOL_CREATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_COMMAND_BUFFER_ALLOCATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_COMMAND_BUFFER_BEGIN_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_COMMAND_BUFFER_END_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_SEMAPHORE_CREATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_FENCE_CREATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_QUEUE_SUBMIT_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_WAIT_FOR_FENCES_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_WAIT_FOR_FENCES_TIMEOUT);
        DEFINE_STATUS_CASE(TEST_VK_BACKING_ALREADY_ALLOCATED);
        DEFINE_STATUS_CASE(TEST_VK_BUFFER_NAME_TOO_LONG);
        DEFINE_STATUS_CASE(TEST_VK_BACKING_SIZE_IS_ZERO);
        DEFINE_STATUS_CASE(TEST_VK_BACKING_NOT_ALLOCATED);
        DEFINE_STATUS_CASE(TEST_VK_BACKING_STILL_ALLOCATED);
        DEFINE_STATUS_CASE(TEST_VK_UNKNOWN_BUFFER_TYPE);
        DEFINE_STATUS_CASE(TEST_VK_SHADER_DESCRIPTORS_ALREADY_CREATED);
        DEFINE_STATUS_CASE(TEST_VK_SHADER_ZERO_SIZED_DESCRIPTOR_SET);
        DEFINE_STATUS_CASE(TEST_VK_SHADER_DESCRIPTORS_NOT_CREATED);
        DEFINE_STATUS_CASE(TEST_VK_COMPUTE_PIPELINE_SHADER_STAGE_MISMATCH);
        DEFINE_STATUS_CASE(TEST_VK_BINDING_UNKNOWN_DESCRIPTOR);
        DEFINE_STATUS_CASE(TEST_VK_BINDING_UNKNOWN_MEMORY_REGION);
        DEFINE_STATUS_CASE(TEST_VK_OUT_OF_COMMAND_BUFFERS);
        DEFINE_STATUS_CASE(TEST_VK_COMMAND_SEQUENCE_ALREADY_STARTED);
        DEFINE_STATUS_CASE(TEST_VK_COMMAND_SEQUENCE_NOT_STARTED);
        DEFINE_STATUS_CASE(TEST_VK_COMMAND_BUFFER_RESET_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_DISPATCH_TOO_LARGE);
        DEFINE_STATUS_CASE(TEST_VK_MEMORY_MAPPING_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_IMAGE_CREATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_IMAGE_BIND_MEMORY_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_UNSUPPORTED_IMAGE_LAYOUT_TRANSITION);
        DEFINE_STATUS_CASE(TEST_VK_BINDING_UNKNOWN_TEXTURE);
        DEFINE_STATUS_CASE(TEST_VK_IMAGE_VIEW_CREATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_SAMPLER_CREATION_ERROR);
        DEFINE_STATUS_CASE(TEST_VK_WORKGROUP_COUNT_NOT_DIVISIBLE);
        DEFINE_STATUS_CASE(TEST_VK_FEATURE_UNSUPPORTED);
        DEFINE_STATUS_CASE(TEST_VK_INVALID_QUEUE_INDEX);
        DEFINE_STATUS_CASE(TEST_VK_COMMAND_SEQUENCE_NOT_MULTI_QUEUE);
        DEFINE_STATUS_CASE(TEST_VK_WAIT_FOR_FENCES_NOT_READY);
    default:
        return "- MISSING LOOKUP TRANSLATION -";
    }
}